from . import capacity_line
from . import capacity_role
from . import hr_employee
from . import product_template
from . import sale_order
from . import sale_order_line
from . import res_company
from . import hr_leave
from . import project_task
from . import account_analytic_line
from . import res_config_settings
from . import resource_calendar_leaves
from . import project_project_stage
from . import project_project
