[project]
name = "odoo-addons-oca-project"
version = "19.0.20260901.0"
dependencies = [
    "odoo-addon-project_administrator_restricted_visibility==19.0.*",
    "odoo-addon-project_department==19.0.*",
    "odoo-addon-project_group==19.0.*",
    "odoo-addon-project_hr==19.0.*",
    "odoo-addon-project_hr_expense_analytic==19.0.*",
    "odoo-addon-project_kanban_form_direct_access==19.0.*",
    "odoo-addon-project_key==19.0.*",
    "odoo-addon-project_merge==19.0.*",
    "odoo-addon-project_milestone_status==19.0.*",
    "odoo-addon-project_parent==19.0.*",
    "odoo-addon-project_parent_task_filter==19.0.*",
    "odoo-addon-project_pivot==19.0.*",
    "odoo-addon-project_sequence==19.0.*",
    "odoo-addon-project_stage_extra_info==19.0.*",
    "odoo-addon-project_tag_hierarchy==19.0.*",
    "odoo-addon-project_tag_multicompany==19.0.*",
    "odoo-addon-project_tag_security==19.0.*",
    "odoo-addon-project_task_ancestor==19.0.*",
    "odoo-addon-project_task_code==19.0.*",
    "odoo-addon-project_task_customer_ref==19.0.*",
    "odoo-addon-project_task_default_stage==19.0.*",
    "odoo-addon-project_task_default_user==19.0.*",
    "odoo-addon-project_task_description_template==19.0.*",
    "odoo-addon-project_task_name_with_id==19.0.*",
    "odoo-addon-project_task_note==19.0.*",
    "odoo-addon-project_task_parent_due_auto==19.0.*",
    "odoo-addon-project_task_personal_stage_auto_fold==19.0.*",
    "odoo-addon-project_task_product==19.0.*",
    "odoo-addon-project_task_product_stock==19.0.*",
    "odoo-addon-project_task_pull_request==19.0.*",
    "odoo-addon-project_task_pull_request_state==19.0.*",
    "odoo-addon-project_task_stage_auto_state==19.0.*",
    "odoo-addon-project_task_stage_mgmt==19.0.*",
    "odoo-addon-project_task_stage_state==19.0.*",
    "odoo-addon-project_task_tag==19.0.*",
    "odoo-addon-project_timeline==19.0.*",
    "odoo-addon-project_timeline_hr_timesheet==19.0.*",
    "odoo-addon-project_type==19.0.*",
    "odoo-addon-project_version==19.0.*",
    "odoo-addon-sale_project_copy_tasks==19.0.*",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 19.0",
]
