[project]
name = "odoo-addons-oca-project"
version = "19.0.20260303.1"
dependencies = [
    "odoo-addon-project_department==19.0.*",
    "odoo-addon-project_task_default_stage==19.0.*",
    "odoo-addon-project_task_description_template==19.0.*",
    "odoo-addon-project_task_name_with_id==19.0.*",
    "odoo-addon-project_task_note==19.0.*",
    "odoo-addon-project_task_pull_request==19.0.*",
    "odoo-addon-project_task_pull_request_state==19.0.*",
    "odoo-addon-project_task_stage_mgmt==19.0.*",
    "odoo-addon-project_task_stage_state==19.0.*",
    "odoo-addon-project_type==19.0.*",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 19.0",
]
